---
# Test duration in seconds (defaults to 86400 which is 24h)
test_duration: "86400"

# How many workers of each type to run
# The default of zero will give as many workers as there are CPUs in the system
cpu_workers: "0"
vm_workers: "0"
hdd_workers: "0"
memrate_workers: "0"

# How many bytes to write per HDD and VM worker
# To calculate the actual usage by the test, multiply hese by the number of
# workers
# Defaults to 256M for both
bytes_per_hdd_worker: "256M"
bytes_per_vm_worker: "256M"

cpu_load: "50"
hdd_opts: "direct,wr-rnd,rd-rnd"
hdd_write_size: "4096"
memory_write_mbs: "10"

# Temporary/runtime directory for stress-ng
stress_tmp_dir: /root/stress-tmp

# We need the ability to skip the screen test if travis run the playbook
# multiple times
skip_screen_check: False
